#!/usr/bin/env python
# ex:set ts=2:

import sys
sys.path.append("..")
from occupancy import *


def occupancysimple (i):
  daycount = 6
  print " Test "+str(i)+": Simple Occupancy Model"
  
  occ = OccupancySimple(daycount, 2)
  
  for i in range(daycount):
    print "   +-- day "+str(i)
    for h in range(24):
      print "   |"+("*"*int(occ.index(i*secsperday+h*3600)))
  
  print "   Done\n"


tests = [occupancysimple,
        ]
print "Running self-test:\n"
for i in range(len(tests)):
  test = tests[i]
  test(i)

